import { Badge } from "@/components/ui/badge"
import { nunito_sans, quando } from "@/app/fonts"

export default function CollectionInfo() {
	return (
		<div className="flex justify-center items-center">
			<div className="max-w-4xl w-3/4 space-y-6">
				<div className="flex flex-col gap-2 justify-left items-center md:flex-row">
					<div className="size-4 bg-red rounded-sm min-w-4 min-h-4"></div>
					<div className="size-4 bg-blue rounded-sm min-w-4 min-h-4"></div>
					<div className="size-4 bg-violet rounded-sm min-w-4 min-h-4"></div>
				<h1 className="text-4xl font-bold text-center">What&apos;s maomao Originals?</h1>
				</div>
				<div className="flex flex-row">
					<h2 className={`${quando.className} text-lg text-left`}>Description</h2>
				</div>
				<p className={`${nunito_sans.className} text-gray-700 text-sm`}>
					maomao Originals is an animated collection made by lovelylooop and it&apos;s the first 888 items in maomao. It consists of Wearables, Consumables, Keys, Loot Boxes, Gemstones, Goods and Materials. Each of these types of items have their own purpose, functionality, rarity and attributes. You can see a few of them above.
					This collection is closely tied to lovelylooop&apos;s flagship product &apos;maomao&apos;. Stakers of maomao Originals will earn a shared revenue generated by in-game microtransactions.
				</p>
				<h2 className={`${quando.className} text-lg text-left`}>Purpose</h2>
				<p className={`${nunito_sans.className} text-gray-700 text-sm`}>
					Launch lovelylooop. Build maomao. Create beautiful products. Make all dreams come true. Give back to community tenfold.
				</p>
				<h2 className={`${quando.className} text-lg text-left`}>Utility</h2>
				<div className="flex flex-row flex-wrap justify-left gap-2">
					<Badge>Giftbox Airdrops</Badge>
					<Badge>Early Access</Badge>
					<Badge>Starter Loot</Badge>
					<Badge>Revenue Sharing</Badge>
					<Badge>Incentivized Test Realm</Badge>
				</div>
				<h2 className={`${quando.className} text-lg text-left`}>Mint Details</h2>
				<div className="flex flex-row justify-left gap-2">
					<Badge variant="outline">May 20th, 2024</Badge>
					<Badge className="bg-yellow">888</Badge>
					<Badge className="bg-blue">0.88 SOL</Badge>
					<Badge className="bg-pink">4.4%</Badge>
				</div>
			</div>
		</div>
	)
}